### ISSUE TITLE
Solana JSON-RPC API 文档翻译

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/developer-content#1]
1.复制 docs/rpc 目录中的每个文件，以创建一个新文件，在文件扩展名之前添加 .zh，例如，json-structures.mdx -> json-structures.zh.mdx（请不要对存储库中的任何现有文件进行任何修改！）
2.将每个新创建的 .zh.mdx 文件的内容从英语翻译成简体中文。在适用的情况下，某些词汇，如 RPC 方法名称，应保持为英文，以确保一致性和清晰度。如果认为有必要，您可以为未翻译的内容附加简短的中文解释，以提供上下文，例如，getSignaturesForAddress -> getSignaturesForAddress（获取地址的签名）
3.将所有翻译后的文件保存到本存储库中，审核所有内容以确保准确性和完整性，将提交给 Solana Foundation MCM 团队最终审查。

**Comment by xilibi2003** [comment]
Bounty ： 300 USDC  ， 提交截止日期为 2024 年 3 月 3 日

**Comment by 847850277** [comment]
> Bounty ： 300 USDC ， 提交截止日期为 2024 年 3 月 3 日

i want to try，please asign to me. 😄

**Comment by 847850277** [comment]
> 1.复制 docs/rpc 目录中的每个文件，以创建一个新文件，在文件扩展名之前添加 .zh，例如，json-structures.mdx -> json-structures.zh.mdx（请不要对存储库中的任何现有文件进行任何修改！） 2.将每个新创建的 .zh.mdx 文件的内容从英语翻译成简体中文。在适用的情况下，某些词汇，如 RPC 方法名称，应保持为英文，以确保一致性和清晰度。如果认为有必要，您可以为未翻译的内容附加简短的中文解释，以提供上下文，例如，getSignaturesForAddress -> getSignaturesForAddress（获取地址的签名） 3.将所有翻译后的文件保存到您的分叉存储库中，审核所有内容以确保准确性和完整性，将提交给 Solana Foundation MCM 团队最终审查。

这是我的翻译仓库地址，请检查是否符合格式，接下我来将继续完成后续的翻译。https://github.com/847850277/developer-content/tree/translate-zh

**Comment by deanplus** [comment]
格式没问题

**Comment by 847850277** [comment]
@0xdwong @xilibi2003 已经翻译完了，麻烦方便的时候帮忙看下是否可以提pr了。

**Comment by deanplus** [comment]
字段Field的name属性，里面的值应该保持英文，当前是直接翻译了。多个文件都有这个问题。
![截屏2024-03-11 15 19 23](https://github.com/lbc-team/developer-content/assets/121151857/dc78e275-a1ec-41f6-96ec-165ac3d42105)

**Comment by deanplus** [comment]
发现一些多出来的内容，比如[这里](https://github.com/847850277/developer-content/blob/translate-zh/docs/rpc/websocket/blockSubscribe.zh.mdx)好几处地方多了`{" "}`

**Comment by deanplus** [comment]
请重新校对下

**Comment by 847850277** [comment]
> 请重新校对下

好的，我将抽空修复一下。

**Comment by 847850277** [comment]
> 请重新校对下

已经按要求修正了，麻烦抽空检查一下。

**Comment by xilibi2003** [comment]
直接向本仓库提 PR ， PR 的时候可以 Review

**Comment by deanmlittle** [comment]
<img width="1333" alt="image" src="https://github.com/lbc-team/developer-content/assets/10921578/a32effa3-ae1f-4d34-87c1-95ae596c9c83">
上面的這些也要翻譯。

**Comment by 847850277** [comment]
> <img alt="image" width="1333" src="https://private-user-images.githubusercontent.com/10921578/317456869-a32effa3-ae1f-4d34-87c1-95ae596c9c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTg0NDcsIm5iZiI6MTcxMTU5ODE0NywicGF0aCI6Ii8xMDkyMTU3OC8zMTc0NTY4NjktYTMyZWZmYTMtYWUxZi00ZDM0LTg3YzEtOTVhZTU5NmM5YzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzNTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NWIyYThkOTA0NGI0OTY2ZDRiNDA3OTdjYmRiZmM2ZTI1MzBmOTg3MDkyODgyNjhhMjQyOWNjN2YxODZiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s2jHMh9w2Xpz7Epui-lRNZ4VtMIZhu6OgSQu9pDgEvk"> 上面的這些也要翻譯。

感谢提醒，已经增加了该部分的翻译。

**Comment by deanplus** [comment]
> <img alt="image" width="1333" src="https://private-user-images.githubusercontent.com/10921578/317456869-a32effa3-ae1f-4d34-87c1-95ae596c9c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTAxMjgsIm5iZiI6MTcxMTYwOTgyOCwicGF0aCI6Ii8xMDkyMTU3OC8zMTc0NTY4NjktYTMyZWZmYTMtYWUxZi00ZDM0LTg3YzEtOTVhZTU5NmM5YzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA3MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3M2QzOWM4ZWUwZDI3MWIxMGQ0NGU3MWFkM2QyMDY1YzE4ZDhhZjhmMjQ2ODk5ZjdiMThmNjg1NWRjZDE1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gb4R70YLAkknuNj-bi33I_46KRpgX9xtHKiH13BVw68"> 上面的這些也要翻譯。

已经加上了
